### ISSUE TITLE
FFT Implementation Development

### ISSUE THREAD

**Issue by JoshuaAHill** [lancaster-university/codal-microbit-v2#83]
## Description

Experiment with current FFT implementation to try and improve its accuracy, especially when working with the Micro:bit's inbuilt speaker. The current FFT can consisstantly recognise notes when using external speakers, but is not accurate in detecting the exact frequency of the note being played (only that the frequency is distinct to others). Ideally the frequency recognised for each note should be the same when plaeyd with both external and internal speakers.

## Todo

- [ ] Create Branch with current FFT implementation (needs permissions)
- [ ] Experiment with improving FFT accuracy with external speakers
- [ ] Experiment with improving FFT recognition and accuracy with inbuilt v2 speaker

**Comment by microbit-carlos** [comment]
Current PR:
- https://github.com/lancaster-university/codal-microbit-v2/pull/291
